theme: jekyll-theme-minimal
title: Utsha Khondkar
description: Machine Learning Engineer at Chevron
logo: https://media.licdn.com/dms/image/C5603AQG0V592iA6QVA/profile-displayphoto-shrink_400_400/0/1651987426863?e=1681344000&v=beta&t=OC4rRN1qATHxVimj9GOmWKja9jHi6VcCAKJ81RKrM-w
show_downloads: false
